-- Generated by build-migration.sh. GTO Training schema, namespaced to 'gto'.
-- Apply against the shared Supabase project (daily-command-center).
CREATE SCHEMA IF NOT EXISTS gto;
--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: async_poker_actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.async_poker_actions (
    id bigint NOT NULL,
    game_id uuid NOT NULL,
    user_id integer NOT NULL,
    hand_number integer DEFAULT 1 NOT NULL,
    action character varying(20) NOT NULL,
    street character varying(20) DEFAULT 'preflop'::character varying NOT NULL,
    amount_chips integer,
    note text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT async_poker_actions_action_check CHECK (((action)::text = ANY ((ARRAY['check'::character varying, 'call'::character varying, 'bet'::character varying, 'raise'::character varying, 'fold'::character varying, 'pass'::character varying, 'timeout'::character varying, 'join'::character varying, 'leave'::character varying, 'start'::character varying, 'end'::character varying, 'ready_next'::character varying, 'show'::character varying])::text[]))),
    CONSTRAINT async_poker_actions_amount_chips_check CHECK (((amount_chips IS NULL) OR (amount_chips >= 0))),
    CONSTRAINT async_poker_actions_street_check CHECK (((street)::text = ANY ((ARRAY['preflop'::character varying, 'flop'::character varying, 'turn'::character varying, 'river'::character varying])::text[])))
);


--
-- Name: async_poker_actions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.async_poker_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: async_poker_actions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.async_poker_actions_id_seq OWNED BY gto.async_poker_actions.id;


--
-- Name: async_poker_game_players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.async_poker_game_players (
    game_id uuid NOT NULL,
    user_id integer NOT NULL,
    seat_index integer NOT NULL,
    stack_chips integer DEFAULT 1000 NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    joined_at timestamp with time zone DEFAULT now(),
    last_seen_at timestamp with time zone,
    CONSTRAINT async_poker_game_players_seat_index_check CHECK (((seat_index >= 0) AND (seat_index <= 8))),
    CONSTRAINT async_poker_game_players_stack_chips_check CHECK ((stack_chips >= 0)),
    CONSTRAINT async_poker_game_players_status_check CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'folded'::character varying, 'left'::character varying])::text[])))
);


--
-- Name: async_poker_games; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.async_poker_games (
    id uuid NOT NULL,
    host_user_id integer NOT NULL,
    name character varying(120) NOT NULL,
    table_size integer DEFAULT 6 NOT NULL,
    turn_seconds integer DEFAULT 86400 NOT NULL,
    status character varying(20) DEFAULT 'waiting'::character varying NOT NULL,
    current_player_user_id integer,
    current_turn_started_at timestamp with time zone,
    current_turn_expires_at timestamp with time zone,
    hand_number integer DEFAULT 1 NOT NULL,
    pot_chips integer DEFAULT 0 NOT NULL,
    small_blind_chips integer DEFAULT 10 NOT NULL,
    big_blind_chips integer DEFAULT 20 NOT NULL,
    state jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT async_poker_games_big_blind_chips_check CHECK ((big_blind_chips > 0)),
    CONSTRAINT async_poker_games_pot_chips_check CHECK ((pot_chips >= 0)),
    CONSTRAINT async_poker_games_small_blind_chips_check CHECK ((small_blind_chips > 0)),
    CONSTRAINT async_poker_games_status_check CHECK (((status)::text = ANY ((ARRAY['waiting'::character varying, 'active'::character varying, 'finished'::character varying])::text[]))),
    CONSTRAINT async_poker_games_table_size_check CHECK (((table_size >= 2) AND (table_size <= 9))),
    CONSTRAINT async_poker_games_turn_seconds_check CHECK (((turn_seconds >= 5) AND (turn_seconds <= 432000)))
);


--
-- Name: async_poker_npc_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.async_poker_npc_users (
    user_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: bankroll; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.bankroll (
    id integer NOT NULL,
    user_id integer NOT NULL,
    recorded_at timestamp with time zone DEFAULT now(),
    amount numeric NOT NULL,
    game_type character varying(50),
    stakes character varying(50),
    notes text
);


--
-- Name: bankroll_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.bankroll_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bankroll_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.bankroll_id_seq OWNED BY gto.bankroll.id;


--
-- Name: feedback_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.feedback_messages (
    id integer NOT NULL,
    user_id integer,
    reporter_username character varying(30),
    reporter_email character varying(254),
    contact_email character varying(254),
    message text NOT NULL,
    source character varying(200),
    path character varying(500),
    status character varying(20) DEFAULT 'new'::character varying NOT NULL,
    read_at timestamp with time zone,
    read_by integer,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT feedback_messages_status_check CHECK (((status)::text = ANY ((ARRAY['new'::character varying, 'read'::character varying])::text[])))
);


--
-- Name: feedback_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.feedback_messages_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: feedback_messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.feedback_messages_id_seq OWNED BY gto.feedback_messages.id;


--
-- Name: hand_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.hand_history (
    id integer NOT NULL,
    user_id integer NOT NULL,
    profile_id integer,
    played_at timestamp with time zone DEFAULT now(),
    game_type character varying(50),
    "position" character varying(20),
    hero_cards jsonb,
    board jsonb,
    actions jsonb,
    result_bb numeric,
    notes text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: hand_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.hand_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: hand_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.hand_history_id_seq OWNED BY gto.hand_history.id;


--
-- Name: in_app_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.in_app_notifications (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    type character varying(60) NOT NULL,
    title character varying(160) NOT NULL,
    body text NOT NULL,
    action_path character varying(500),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    read_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: in_app_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.in_app_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: in_app_notifications_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.in_app_notifications_id_seq OWNED BY gto.in_app_notifications.id;


--
-- Name: live_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.live_sessions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    client_id uuid NOT NULL,
    name character varying(200),
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone,
    table_size integer NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT live_sessions_table_size_check CHECK (((table_size >= 2) AND (table_size <= 9)))
);


--
-- Name: live_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.live_sessions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: live_sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.live_sessions_id_seq OWNED BY gto.live_sessions.id;


--
-- Name: login_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.login_events (
    id bigint NOT NULL,
    user_id integer,
    username character varying(30),
    email character varying(254),
    method character varying(40) DEFAULT 'password'::character varying NOT NULL,
    ip_address text,
    country character varying(120),
    user_agent text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: login_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.login_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: login_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.login_events_id_seq OWNED BY gto.login_events.id;


--
-- Name: notification_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.notification_preferences (
    user_id integer NOT NULL,
    email_turn_notifications boolean DEFAULT false NOT NULL,
    discord_turn_notifications boolean DEFAULT false NOT NULL,
    discord_user_id character varying(64),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.profiles (
    id integer NOT NULL,
    user_id integer NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(50) DEFAULT 'poker'::character varying NOT NULL,
    table_size integer,
    range_data jsonb,
    postflop_thresholds jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT profiles_table_size_check CHECK (((table_size >= 2) AND (table_size <= 9)))
);


--
-- Name: profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.profiles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: profiles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.profiles_id_seq OWNED BY gto.profiles.id;


--
-- Name: promo_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.promo_codes (
    id integer NOT NULL,
    code character varying(64) NOT NULL,
    tier character varying(20) NOT NULL,
    duration_days integer NOT NULL,
    max_redemptions integer,
    expires_at timestamp with time zone,
    active boolean DEFAULT true NOT NULL,
    created_by integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT promo_codes_duration_days_check CHECK (((duration_days >= 1) AND (duration_days <= 3650))),
    CONSTRAINT promo_codes_max_redemptions_check CHECK (((max_redemptions IS NULL) OR (max_redemptions > 0))),
    CONSTRAINT promo_codes_tier_check CHECK (((tier)::text = ANY ((ARRAY['user'::character varying, 'gold'::character varying, 'platinum'::character varying, 'diamond'::character varying])::text[])))
);


--
-- Name: promo_codes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.promo_codes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: promo_codes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.promo_codes_id_seq OWNED BY gto.promo_codes.id;


--
-- Name: promo_redemptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.promo_redemptions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    promo_code_id integer NOT NULL,
    tier character varying(20) NOT NULL,
    redeemed_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT promo_redemptions_tier_check CHECK (((tier)::text = ANY ((ARRAY['user'::character varying, 'gold'::character varying, 'platinum'::character varying, 'diamond'::character varying])::text[])))
);


--
-- Name: promo_redemptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.promo_redemptions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: promo_redemptions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.promo_redemptions_id_seq OWNED BY gto.promo_redemptions.id;


--
-- Name: scenarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.scenarios (
    id integer NOT NULL,
    user_id integer NOT NULL,
    title character varying(200) NOT NULL,
    game_type character varying(50),
    scenario_data jsonb,
    notes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: scenarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.scenarios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: scenarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.scenarios_id_seq OWNED BY gto.scenarios.id;


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.sessions (
    sid character varying NOT NULL,
    sess json NOT NULL,
    expire timestamp with time zone NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gto.users (
    id integer NOT NULL,
    username character varying(30) NOT NULL,
    password_hash text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    membership_tier character varying(20) DEFAULT 'user'::character varying NOT NULL,
    email character varying(254),
    role character varying(20) DEFAULT 'user'::character varying NOT NULL,
    CONSTRAINT users_membership_tier_check CHECK (((membership_tier)::text = ANY ((ARRAY['user'::character varying, 'gold'::character varying, 'platinum'::character varying, 'diamond'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['user'::character varying, 'admin'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE gto.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE gto.users_id_seq OWNED BY gto.users.id;


--
-- Name: async_poker_actions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.async_poker_actions ALTER COLUMN id SET DEFAULT nextval('gto.async_poker_actions_id_seq'::regclass);


--
-- Name: bankroll id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.bankroll ALTER COLUMN id SET DEFAULT nextval('gto.bankroll_id_seq'::regclass);


--
-- Name: feedback_messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.feedback_messages ALTER COLUMN id SET DEFAULT nextval('gto.feedback_messages_id_seq'::regclass);


--
-- Name: hand_history id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.hand_history ALTER COLUMN id SET DEFAULT nextval('gto.hand_history_id_seq'::regclass);


--
-- Name: in_app_notifications id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.in_app_notifications ALTER COLUMN id SET DEFAULT nextval('gto.in_app_notifications_id_seq'::regclass);


--
-- Name: live_sessions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.live_sessions ALTER COLUMN id SET DEFAULT nextval('gto.live_sessions_id_seq'::regclass);


--
-- Name: login_events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.login_events ALTER COLUMN id SET DEFAULT nextval('gto.login_events_id_seq'::regclass);


--
-- Name: profiles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.profiles ALTER COLUMN id SET DEFAULT nextval('gto.profiles_id_seq'::regclass);


--
-- Name: promo_codes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.promo_codes ALTER COLUMN id SET DEFAULT nextval('gto.promo_codes_id_seq'::regclass);


--
-- Name: promo_redemptions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.promo_redemptions ALTER COLUMN id SET DEFAULT nextval('gto.promo_redemptions_id_seq'::regclass);


--
-- Name: scenarios id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.scenarios ALTER COLUMN id SET DEFAULT nextval('gto.scenarios_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.users ALTER COLUMN id SET DEFAULT nextval('gto.users_id_seq'::regclass);


--
-- Name: async_poker_actions async_poker_actions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.async_poker_actions
    ADD CONSTRAINT async_poker_actions_pkey PRIMARY KEY (id);


--
-- Name: async_poker_game_players async_poker_game_players_game_id_seat_index_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.async_poker_game_players
    ADD CONSTRAINT async_poker_game_players_game_id_seat_index_key UNIQUE (game_id, seat_index);


--
-- Name: async_poker_game_players async_poker_game_players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.async_poker_game_players
    ADD CONSTRAINT async_poker_game_players_pkey PRIMARY KEY (game_id, user_id);


--
-- Name: async_poker_games async_poker_games_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.async_poker_games
    ADD CONSTRAINT async_poker_games_pkey PRIMARY KEY (id);


--
-- Name: async_poker_npc_users async_poker_npc_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.async_poker_npc_users
    ADD CONSTRAINT async_poker_npc_users_pkey PRIMARY KEY (user_id);


--
-- Name: bankroll bankroll_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.bankroll
    ADD CONSTRAINT bankroll_pkey PRIMARY KEY (id);


--
-- Name: feedback_messages feedback_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.feedback_messages
    ADD CONSTRAINT feedback_messages_pkey PRIMARY KEY (id);


--
-- Name: hand_history hand_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.hand_history
    ADD CONSTRAINT hand_history_pkey PRIMARY KEY (id);


--
-- Name: in_app_notifications in_app_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.in_app_notifications
    ADD CONSTRAINT in_app_notifications_pkey PRIMARY KEY (id);


--
-- Name: live_sessions live_sessions_client_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.live_sessions
    ADD CONSTRAINT live_sessions_client_id_key UNIQUE (client_id);


--
-- Name: live_sessions live_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.live_sessions
    ADD CONSTRAINT live_sessions_pkey PRIMARY KEY (id);


--
-- Name: login_events login_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.login_events
    ADD CONSTRAINT login_events_pkey PRIMARY KEY (id);


--
-- Name: notification_preferences notification_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.notification_preferences
    ADD CONSTRAINT notification_preferences_pkey PRIMARY KEY (user_id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: promo_codes promo_codes_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.promo_codes
    ADD CONSTRAINT promo_codes_code_key UNIQUE (code);


--
-- Name: promo_codes promo_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.promo_codes
    ADD CONSTRAINT promo_codes_pkey PRIMARY KEY (id);


--
-- Name: promo_redemptions promo_redemptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.promo_redemptions
    ADD CONSTRAINT promo_redemptions_pkey PRIMARY KEY (id);


--
-- Name: promo_redemptions promo_redemptions_user_id_promo_code_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.promo_redemptions
    ADD CONSTRAINT promo_redemptions_user_id_promo_code_id_key UNIQUE (user_id, promo_code_id);


--
-- Name: scenarios scenarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.scenarios
    ADD CONSTRAINT scenarios_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (sid);


--
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: idx_async_poker_actions_game_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_async_poker_actions_game_created ON gto.async_poker_actions USING btree (game_id, created_at DESC);


--
-- Name: idx_async_poker_actions_game_hand_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_async_poker_actions_game_hand_created ON gto.async_poker_actions USING btree (game_id, hand_number DESC, created_at DESC);


--
-- Name: idx_async_poker_games_current_player; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_async_poker_games_current_player ON gto.async_poker_games USING btree (current_player_user_id, current_turn_expires_at);


--
-- Name: idx_async_poker_games_status_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_async_poker_games_status_updated ON gto.async_poker_games USING btree (status, updated_at DESC);


--
-- Name: idx_async_poker_players_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_async_poker_players_user ON gto.async_poker_game_players USING btree (user_id, joined_at DESC);


--
-- Name: idx_feedback_messages_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_feedback_messages_status_created ON gto.feedback_messages USING btree (status, created_at DESC);


--
-- Name: idx_in_app_notifications_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_in_app_notifications_user_created ON gto.in_app_notifications USING btree (user_id, created_at DESC);


--
-- Name: idx_in_app_notifications_user_unread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_in_app_notifications_user_unread ON gto.in_app_notifications USING btree (user_id, read_at) WHERE (read_at IS NULL);


--
-- Name: idx_live_sessions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_live_sessions_user ON gto.live_sessions USING btree (user_id, started_at DESC);


--
-- Name: idx_login_events_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_events_created ON gto.login_events USING btree (created_at DESC);


--
-- Name: idx_login_events_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_events_user_created ON gto.login_events USING btree (user_id, created_at DESC);


--
-- Name: idx_promo_codes_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_promo_codes_code ON gto.promo_codes USING btree (code);


--
-- Name: idx_promo_redemptions_user_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_promo_redemptions_user_active ON gto.promo_redemptions USING btree (user_id, expires_at DESC);


--
-- Name: idx_session_expire; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_expire ON gto.sessions USING btree (expire);


--
-- Name: async_poker_actions async_poker_actions_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.async_poker_actions
    ADD CONSTRAINT async_poker_actions_game_id_fkey FOREIGN KEY (game_id) REFERENCES gto.async_poker_games(id) ON DELETE CASCADE;


--
-- Name: async_poker_game_players async_poker_game_players_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.async_poker_game_players
    ADD CONSTRAINT async_poker_game_players_game_id_fkey FOREIGN KEY (game_id) REFERENCES gto.async_poker_games(id) ON DELETE CASCADE;


--
-- Name: bankroll bankroll_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.bankroll
    ADD CONSTRAINT bankroll_user_id_fkey FOREIGN KEY (user_id) REFERENCES gto.users(id) ON DELETE CASCADE;


--
-- Name: feedback_messages feedback_messages_read_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.feedback_messages
    ADD CONSTRAINT feedback_messages_read_by_fkey FOREIGN KEY (read_by) REFERENCES gto.users(id) ON DELETE SET NULL;


--
-- Name: feedback_messages feedback_messages_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.feedback_messages
    ADD CONSTRAINT feedback_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES gto.users(id) ON DELETE SET NULL;


--
-- Name: hand_history hand_history_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.hand_history
    ADD CONSTRAINT hand_history_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES gto.profiles(id) ON DELETE SET NULL;


--
-- Name: hand_history hand_history_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.hand_history
    ADD CONSTRAINT hand_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES gto.users(id) ON DELETE CASCADE;


--
-- Name: live_sessions live_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.live_sessions
    ADD CONSTRAINT live_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES gto.users(id) ON DELETE CASCADE;


--
-- Name: login_events login_events_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.login_events
    ADD CONSTRAINT login_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES gto.users(id) ON DELETE SET NULL;


--
-- Name: profiles profiles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.profiles
    ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES gto.users(id) ON DELETE CASCADE;


--
-- Name: promo_codes promo_codes_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.promo_codes
    ADD CONSTRAINT promo_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES gto.users(id) ON DELETE SET NULL;


--
-- Name: promo_redemptions promo_redemptions_promo_code_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.promo_redemptions
    ADD CONSTRAINT promo_redemptions_promo_code_id_fkey FOREIGN KEY (promo_code_id) REFERENCES gto.promo_codes(id) ON DELETE CASCADE;


--
-- Name: promo_redemptions promo_redemptions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.promo_redemptions
    ADD CONSTRAINT promo_redemptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES gto.users(id) ON DELETE CASCADE;


--
-- Name: scenarios scenarios_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gto.scenarios
    ADD CONSTRAINT scenarios_user_id_fkey FOREIGN KEY (user_id) REFERENCES gto.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


