#!/usr/bin/env bash
# Regenerate the gto-schema consolidation artifacts from the live GTO source DB.
#
# Moves the GTO Training database (standalone Supabase project
# svqwyibsmhpknnjvbufi, public schema) into a dedicated `gto` schema so it can
# live inside the shared daily-command-center Supabase project alongside other
# apps without colliding on generic table names (users, sessions, ...).
#
# Reads SOURCE_DATABASE_URL (falls back to DATABASE_URL from ../../.env).
# Produces, in this directory:
#   01_schema_gto.sql  - DDL, every object namespaced into schema `gto`
#   02_data_gto.sql    - data-only INSERTs + sequence setvals, namespaced to gto
# Both are safe to run with psql against the target. Apply 01 then 02.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$here/../.." && pwd)"
cd "$repo_root"

# Resolve source connection string.
if [[ -z "${SOURCE_DATABASE_URL:-}" ]]; then
  # shellcheck disable=SC1091
  set -a; . ./.env; set +a
  SOURCE_DATABASE_URL="${DATABASE_URL:?DATABASE_URL not found in .env}"
fi
export PGCONNECT_TIMEOUT=20

EXCLUDE="--exclude-table=public.async_poker_schema_probe"   # diagnostic artifact, 0 rows
COMMON="--schema=public --no-owner --no-acl $EXCLUDE"

echo "[build] dumping schema..."
pg_dump "$SOURCE_DATABASE_URL" --schema-only --no-comments $COMMON -f "$here/_raw_schema.sql"

echo "[build] dumping data..."
pg_dump "$SOURCE_DATABASE_URL" --data-only --inserts $COMMON -f "$here/_raw_data.sql"

echo "[build] transforming schema -> gto..."
{
  echo "-- Generated by build-migration.sh. GTO Training schema, namespaced to 'gto'."
  echo "-- Apply against the shared Supabase project (daily-command-center)."
  echo "CREATE SCHEMA IF NOT EXISTS gto;"
  # Every public. in a schema-only dump is an object qualifier; safe global swap.
  # Drop psql \restrict/\unrestrict guards (pg18) and the redundant CREATE SCHEMA public.
  sed -E \
    -e '/^\\(restrict|unrestrict)/d' \
    -e '/^CREATE SCHEMA public;/d' \
    -e 's/\bpublic\./gto./g' \
    "$here/_raw_schema.sql"
} > "$here/01_schema_gto.sql"

echo "[build] transforming data -> gto..."
{
  echo "-- Generated by build-migration.sh. GTO Training row data, namespaced to 'gto'."
  echo "-- pg_dump emits rows in FK-dependency order (parents before children), so a"
  echo "-- plain transaction loads cleanly without needing superuser trigger-disabling"
  echo "-- (the Supabase 'postgres' role can't SET session_replication_role)."
  echo "BEGIN;"
  # Anchored rewrites only: never touch JSONB/text payloads inside a VALUES list.
  sed -E \
    -e '/^\\(restrict|unrestrict)/d' \
    -e 's/^INSERT INTO public\./INSERT INTO gto./' \
    -e "s/^SELECT pg_catalog\\.setval\\('public\\./SELECT pg_catalog.setval('gto./" \
    "$here/_raw_data.sql"
  echo "COMMIT;"
} > "$here/02_data_gto.sql"

echo "[build] done:"
wc -l "$here/01_schema_gto.sql" "$here/02_data_gto.sql"
