param(
  [string]$ProdDatabaseUrl = "",
  [string]$LocalDatabaseUrl = "",
  [string]$DumpFile = "",
  [string[]]$Schemas = @("public"),
  [switch]$SkipDump,
  [switch]$KeepDump
)

$ErrorActionPreference = "Stop"
$env:PGCLIENTENCODING = "UTF8"

function Require-Command([string]$Name) {
  $command = Get-Command $Name -ErrorAction SilentlyContinue
  if (-not $command) {
    throw "Missing PostgreSQL command '$Name'. Install PostgreSQL tools and make sure '$Name' is on PATH."
  }
  return $command.Source
}

function Read-DotEnv([string]$Path) {
  $values = @{}
  if (-not (Test-Path $Path)) {
    return $values
  }

  foreach ($line in Get-Content $Path) {
    if ($line -match '^\s*#' -or $line -notmatch '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$') {
      continue
    }
    $key = $matches[1]
    $value = $matches[2].Trim()
    if (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'"))) {
      $value = $value.Substring(1, $value.Length - 2)
    }
    $values[$key] = $value
  }
  return $values
}

function Get-DatabaseName([string]$ConnectionString) {
  $uri = [System.Uri]$ConnectionString
  $name = $uri.AbsolutePath.Trim("/")
  if (-not $name) {
    throw "LocalDatabaseUrl must include a database name."
  }
  return [System.Uri]::UnescapeDataString($name)
}

function Get-MaintenanceUrl([string]$ConnectionString) {
  $builder = [System.UriBuilder]$ConnectionString
  $builder.Path = "postgres"
  return $builder.Uri.AbsoluteUri
}

function Invoke-PostgresCommand([scriptblock]$Command, [string]$FailureMessage) {
  & $Command
  if ($LASTEXITCODE -ne 0) {
    throw $FailureMessage
  }
}

$repoRoot = Get-Location
$envValues = Read-DotEnv (Join-Path $repoRoot ".env")

if (-not $ProdDatabaseUrl) {
  if ($env:PROD_DATABASE_URL) {
    $ProdDatabaseUrl = $env:PROD_DATABASE_URL
  } elseif ($envValues.ContainsKey("PROD_DATABASE_URL")) {
    $ProdDatabaseUrl = $envValues["PROD_DATABASE_URL"]
  } elseif ($env:DATABASE_URL) {
    $ProdDatabaseUrl = $env:DATABASE_URL
  } elseif ($envValues.ContainsKey("DATABASE_URL")) {
    $ProdDatabaseUrl = $envValues["DATABASE_URL"]
  }
}

if (-not $ProdDatabaseUrl -and -not $SkipDump) {
  throw "No production database URL found. Set PROD_DATABASE_URL, DATABASE_URL, or pass -ProdDatabaseUrl."
}

if (-not $LocalDatabaseUrl) {
  if ($env:LOCAL_DATABASE_URL) {
    $LocalDatabaseUrl = $env:LOCAL_DATABASE_URL
  } elseif ($envValues.ContainsKey("LOCAL_DATABASE_URL")) {
    $LocalDatabaseUrl = $envValues["LOCAL_DATABASE_URL"]
  } else {
    $LocalDatabaseUrl = "postgresql://postgres@127.0.0.1:55432/gto_training_local"
  }
}

$pgDump = Require-Command "pg_dump"
$pgRestore = Require-Command "pg_restore"
$psql = Require-Command "psql"

& (Join-Path $repoRoot "scripts/start-local-postgres.ps1")

$dumpDir = Join-Path $repoRoot "db/dumps"
New-Item -ItemType Directory -Force -Path $dumpDir | Out-Null

if (-not $DumpFile) {
  $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
  $DumpFile = Join-Path $dumpDir "prod-$timestamp.dump"
}

if (-not $SkipDump) {
  Write-Host "Dumping production database to $DumpFile"
  $schemaArgs = @()
  foreach ($schema in $Schemas) {
    if ($schema.Trim()) {
      $schemaArgs += "--schema"
      $schemaArgs += $schema.Trim()
    }
  }
  Invoke-PostgresCommand {
    & $pgDump --format=custom --no-owner --no-privileges @schemaArgs --file $DumpFile $ProdDatabaseUrl
  } "pg_dump failed. Check the production DATABASE_URL and network access."
} elseif (-not (Test-Path $DumpFile)) {
  throw "SkipDump was supplied, but dump file does not exist: $DumpFile"
}

$localDbName = Get-DatabaseName $LocalDatabaseUrl
$maintenanceUrl = Get-MaintenanceUrl $LocalDatabaseUrl

Write-Host "Recreating local database '$localDbName'"
Invoke-PostgresCommand {
  & $psql $maintenanceUrl -v ON_ERROR_STOP=1 -c "DROP DATABASE IF EXISTS `"$localDbName`" WITH (FORCE);"
} "Failed to drop local database '$localDbName'."

Invoke-PostgresCommand {
  & $psql $maintenanceUrl -v ON_ERROR_STOP=1 -c "CREATE DATABASE `"$localDbName`" ENCODING 'UTF8' TEMPLATE template0;"
} "Failed to create local database '$localDbName'."

Write-Host "Restoring dump into local database"
Invoke-PostgresCommand {
  & $pgRestore --clean --if-exists --no-owner --no-privileges --dbname $LocalDatabaseUrl $DumpFile
} "pg_restore failed."

Write-Host "Applying repo schema to bring local database up to date"
Invoke-PostgresCommand {
  & $psql $LocalDatabaseUrl -v ON_ERROR_STOP=1 -f (Join-Path $repoRoot "db/schema.sql")
} "Applying db/schema.sql failed."

$envLocalPath = Join-Path $repoRoot ".env.local"
$lines = @(
  "# Generated by scripts/refresh-local-db.ps1",
  "# Use with: npm run dev:server:local",
  "DATABASE_URL=$LocalDatabaseUrl"
)

foreach ($key in @("SESSION_SECRET", "PORT", "ADMIN_EMAILS", "BUG_NOTIFICATION_EMAILS", "NOTIFICATION_FROM_EMAIL", "WELCOME_FROM_EMAIL", "RESEND_API_KEY", "DISCORD_TURN_WEBHOOK_URL", "CLOUDFLARE_ACCESS_ENABLED", "CLOUDFLARE_ACCESS_TEAM_DOMAIN", "CLOUDFLARE_ACCESS_AUD")) {
  if ($envValues.ContainsKey($key)) {
    $lines += "$key=$($envValues[$key])"
  }
}

$lines += "SKIP_SCHEMA_INIT=false"
Set-Content -Path $envLocalPath -Value $lines -Encoding utf8

if (-not $KeepDump -and (Test-Path $DumpFile)) {
  Remove-Item -LiteralPath $DumpFile
  Write-Host "Removed temporary dump file. Pass -KeepDump to retain it."
}

Write-Host "Local database refresh complete."
Write-Host "Local DATABASE_URL: $LocalDatabaseUrl"
Write-Host "Generated env file: $envLocalPath"
